version: "3"

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my-users"

  redis:
    image: redis
    ports:
      - 6379:6379

  lift-web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/lift-web"
      - "/opt/lift-web/target"
      - "/opt/lift-web/project/target"
    environment:
      POSTGRES_DB: "my-users"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_SERVER: "postgres"
      POSTGRES_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"